name: 'adventureworks_dbt'
version: '1.0'
config-version: 2

profile: 'adventureworks_profile'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target"]

models:
  adventureworks_dbt:
    +schema: dbo
    +materialized: view

