adventureworks_profile:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: sqlserver
      port: 1433
      user: sa
      password: "{{ env_var('MSSQL_SA_PASSWORD') }}"
      database: AdventureWorks_Staging
      schema: dbo
      trust_cert: True
      encrypt: True
      authentication: 'sql'

