version: 2

models:
  - name: stg_sales_orders
    columns:
      - name: total_due
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10000
